# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true
build:
    image: default-jammy
    nodes:
        analysis:
            environment:
                php:
                    version: 8.2
    tests:
        override:
            -
                command: 'XDEBUG_MODE=coverage bin/phpunit --coverage-clover=.coverage'
                coverage:
                    file: '.coverage'
                    format: 'clover'
