# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php:
            version: 8.2.0
    tests:
        override:
            -
                command: 'bin/phpunit --coverage-clover=.coverage'
                coverage:
                    file: '.coverage'
                    format: 'clover'
