# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php:
            version: 8.2.0
    image: default-jammy
    tests:
        override:
            -
                command: 'XDEBUG_MODE=coverage bin/phpunit --coverage-clover=.coverage'
                coverage:
                    file: '.coverage'
                    format: 'clover'
